version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm start
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
